/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 5;
  /** RegularExpression Id. */
  int TABLE = 6;
  /** RegularExpression Id. */
  int PRIMARY = 7;
  /** RegularExpression Id. */
  int FOREIGN = 8;
  /** RegularExpression Id. */
  int KEY = 9;
  /** RegularExpression Id. */
  int REFERENCES = 10;
  /** RegularExpression Id. */
  int DROP = 11;
  /** RegularExpression Id. */
  int INSERT = 12;
  /** RegularExpression Id. */
  int INTO = 13;
  /** RegularExpression Id. */
  int DELETE = 14;
  /** RegularExpression Id. */
  int FROM = 15;
  /** RegularExpression Id. */
  int SHOW = 16;
  /** RegularExpression Id. */
  int TABLES = 17;
  /** RegularExpression Id. */
  int EXIT = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int CHAR = 20;
  /** RegularExpression Id. */
  int DATE = 21;
  /** RegularExpression Id. */
  int DESC = 22;
  /** RegularExpression Id. */
  int SELECT = 23;
  /** RegularExpression Id. */
  int AS = 24;
  /** RegularExpression Id. */
  int WHERE = 25;
  /** RegularExpression Id. */
  int OR = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int NOT = 28;
  /** RegularExpression Id. */
  int NULL = 29;
  /** RegularExpression Id. */
  int IS = 30;
  /** RegularExpression Id. */
  int VALUES = 31;
  /** RegularExpression Id. */
  int SEMICOLON = 32;
  /** RegularExpression Id. */
  int LEFT_PAREN = 33;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int UNDERSCORE = 36;
  /** RegularExpression Id. */
  int INT_VALUE = 37;
  /** RegularExpression Id. */
  int SIGN = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 40;
  /** RegularExpression Id. */
  int ALPHABET = 41;
  /** RegularExpression Id. */
  int WILDCARD = 42;
  /** RegularExpression Id. */
  int PERIOD = 43;
  /** RegularExpression Id. */
  int COMP_OP = 44;
  /** RegularExpression Id. */
  int DATE_VALUE = 45;
  /** RegularExpression Id. */
  int NNNN = 46;
  /** RegularExpression Id. */
  int NN = 47;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 48;
  /** RegularExpression Id. */
  int QUOTE = 49;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTERS = 50;
  /** RegularExpression Id. */
  int CHAR_STRING = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"create\"",
    "\"table\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"references\"",
    "\"drop\"",
    "\"insert\"",
    "\"into\"",
    "\"delete\"",
    "\"from\"",
    "\"show\"",
    "\"tables\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"desc\"",
    "\"select\"",
    "\"as\"",
    "\"where\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"null\"",
    "\"is\"",
    "\"values\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"_\"",
    "<INT_VALUE>",
    "<SIGN>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "\"*\"",
    "\".\"",
    "<COMP_OP>",
    "<DATE_VALUE>",
    "<NNNN>",
    "<NN>",
    "<NON_QUOTE_CHARACTER>",
    "\"\\\'\"",
    "<NON_QUOTE_SPECIAL_CHARACTERS>",
    "<CHAR_STRING>",
  };

}
